### ISSUE TITLE
No scaling_governor on virtualized environments

### ISSUE THREAD

**Issue by localh0t** [andresriancho/pico#49]
**scaling_governor** files under certain VMware environments seems to not exist:

```
# l "/sys/devices/system/cpu/cpu*/cpufreq/scaling_governor"
ls: cannot access '/sys/devices/system/cpu/cpu*/cpufreq/scaling_governor': No such file or directory
```
### My configuration:
- VM: Xubuntu 16.04 x64
- Host: Xubuntu 16.04 x64
- Processors assigned: 2
- Version: VMware 12.1.1
### This leads to:

```
# python timing-collector.py testTiming1
Traceback (most recent call last):
  File "timing-collector.py", line 197, in <module>
    clear_os_settings(tcpts_previous)
  File "timing-collector.py", line 169, in clear_os_settings
    setPowersave(True)
  File "/tmp/pico/utils/os_utils.py", line 75, in setPowersave
    'r+b')
IOError: [Errno 2] No such file or directory: '/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor'
```

Should there be a check if the files exist first?

**Comment by andresriancho** [comment]
@localh0t you rock :+1: , this tool isn't even released and you're already reporting issues. I agree, there should be a check, thanks for noticing.

If you're interested in helping with the development and tests of this tool let me know. I'll be spending considerable time on it
